/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyectGrafo;

import adacters.GraphAdacter;
import interfac.GraphVisualizer;


public class App {
    private static DataManager dataManager;

    /**
     * Punto de entrada principal del programa.
     * Carga los datos desde un archivo, crea una instancia de DataManager y muestra el grafo en un panel de visualización.
     */
    public static void main(String[] args) {
        try {
            // Crear instancia de DataManager
            dataManager = new DataManager();

            // Cargar datos del archivo
            dataManager.loadFromFile();

            // Obtener el graphAdacter del DataManager
            GraphAdacter graphAdacter = dataManager.getGraph();
            graphAdacter.updateGraph();

            // Configurar el panel de visualización del graphAdacter
            GraphVisualizer gv = new GraphVisualizer(graphAdacter);
            gv.showGraph();

        } catch (Exception e) {
            // Manejar cualquier excepción lanzada durante la ejecución
            e.printStackTrace();
        } finally {
            // Realizar acciones de limpieza o liberación de recursos, si es necesario
        }
    }


    /**
     * Obtiene la instancia de DataManager.
     *
     * @return La instancia de DataManager.
     */
    public static DataManager getDataManager() {
        return dataManager;
    }

}
